project:
  type: book

book:
  title: "Analysis in High-Energy Physics as a Differentiable Program"
  author: "Nathan Simpson"
  date: "15/08/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Fundamentals"
      chapters:
        - stat-fundamentals.qmd
        - stat-practical.qmd
        - autodiff.qmd
        - opt.qmd
        - diffprog.qmd
    - part: "Applications"
      chapters:
      - diffprog-hep.qmd
      - flow-interp.qmd
      - sh.qmd
    - references.qmd
  appendices:
    - software.qmd
    - trt.qmd
    - clarinet.qmd


bibliography: references.bib
pdf-engine: pdflatex
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
