project:
  type: book

book:
  title: "Data Analysis in High-Energy Physics as a Differentiable Program"
  author: "Nathan Simpson"
  date: "02/03/2023"
  chapters:
    - index.qmd
    - part: "Fundamentals"
      chapters:
        - physics.qmd
        - stat-fundamentals.qmd
        - stat-practical.qmd
        - diffprog.qmd
        - autodiff.qmd
        - ml.qmd
    - part: "Applications"
      chapters:
      - diffprog-hep.qmd
      - flow-interp.qmd
      - sh.qmd
    - references.qmd
  appendices:
    - neos-extra.qmd

execute:
  freeze: auto

bibliography: references.bib
pdf-engine: pdflatex
# cite-method: biblatex
# biblatexoptions: citestyle=numeric
format:
  html:
    theme: sketchy
  pdf:
    documentclass: scrreprt
    # cite-method: biblatex
    keep-tex: true
    #
