project:
  type: book

book:
  title: "Analysis in High-Energy Physics as a Differentiable Program"
  author: "Nathan Simpson"
  date: "15/08/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
    - part: stat-fundamentals.ipynb
    - part: stat-practical.ipynb
    - part: diffprog.ipynb
    - part: ml.ipynb
    - part: neos.ipynb
    - part: flow-interp.ipynb
    - part: sh.ipynb
  appendices:
    - software.ipynb
    - trt.ipynb
    - clarinet.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
