project:
  type: book

book:
  title: "Analysis in High-Energy Physics as a Differentiable Program"
  author: "Nathan Simpson"
  date: "15/08/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Fundamentals"
      chapters:
            - stat-fundamentals.ipynb
            - stat-practical.ipynb
            - diffprog.ipynb
            - ml.ipynb
    - part: "Applications"
      chapters:
      - neos.ipynb
      - flow-interp.ipynb
      - sh.ipynb
    - references.qmd
  appendices:
    - software.ipynb
    - trt.ipynb
    - clarinet.ipynb


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
