project:
  type: book

book:
  title: "Data Analysis in High-Energy Physics as a Differentiable Program"
  author: "Nathan Simpson"
  date: "15/08/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Fundamentals"
      chapters:
        - physics.qmd
        - stat-fundamentals.qmd
        - stat-practical.qmd
        - diffprog.qmd
        - autodiff.qmd
        - ml.qmd
    - part: "Applications"
      chapters:
      - diffprog-hep.qmd
      - flow-interp.qmd
      - sh.qmd
    - references.qmd
  appendices:
    - software.qmd
    - trt.qmd
    - clarinet.qmd


bibliography: references.bib
pdf-engine: xelatex
cite-method: biblatex
biblatexoptions: citestyle=numeric
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    # cite-method: biblatex
    keep-tex: true
    #
