project:
  type: book

book:
  title: "Analysis in High-Energy Physics as a Differentiable Program"
  author: "Nathan Simpson"
  date: "15/08/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Fundamentals"
      chapters:
        - stat-fundamentals.qmd
        - stat-practical.ipynb
        - autodiff.qmd
        - opt.ipynb
        - diffprog.ipynb
    - part: "Applications"
      chapters:
      - diffprog-hep.qmd
      - flow-interp.ipynb
      - sh.ipynb
    - references.qmd
  appendices:
    - software.ipynb
    - trt.ipynb
    - clarinet.ipynb


bibliography: references.bib
pdf-engine: pdflatex
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
