project:
  type: book

book:
  title: "Data Analysis in High-Energy Physics as a Differentiable Program"
  date: "02/03/2023"
  author:
    - name: Nathan Simpson
      url: https://phinate.github.io
      affiliation: Lund University
  citation:
    type: thesis
    doi: "10.5281/zenodo.7520314"
    url: https://phinate.github.io/thesis
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: "Fundamentals"
      chapters:
        - physics.qmd
        - stat-fundamentals.qmd
        - stat-practical.qmd
        - diffprog.qmd
        - autodiff.qmd
        - ml.qmd
    - part: "Applications"
      chapters:
      - diffprog-hep.qmd
      - flow-interp.qmd
      - sh.qmd
    - references.qmd
  appendices:
    - neos-extra.qmd

execute:
  freeze: auto 
website:
  twitter-card: true
bibliography: references.bib
pdf-engine: pdflatex
# cite-method: biblatex
# biblatexoptions: citestyle=numeric
format:
  html:
    toc-location: right
    toc-title: "On this page:"
    code-copy: true
    theme: 
      - united
      - custom.scss
